name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
    poisonwater:
        description: Utility command for PoisonWater plugin
        permission: poisonwater.admin
        usage: /<command>

permissions:
    poisonwater.admin:
        default: op